apiVersion: v1
kind: Deployment
metadata:
  name: myapp-rc
  labels: # any additional metadata
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels: # any additional metadata
        app: myapp
        type: pod
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: size
                    operator: In
                    values:
                      - Large
                      - Medium
      containers:
        - name: nginx-container
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          # ports:
          #   - containerPort: 1000
  replicas: 3
  selector:
    app: myapp
    type: front-end
