apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels: # any additional metadata
    app: myapp
    type: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    # ports:
    #   - containerPort: 1000
