apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels: # any additional metadata
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels: # any additional metadata
        app: myapp
        type: pod
    spec:
      containers:
      - name: nginx-container
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
  replicas: 3
  selector:
    matchLabels:
      type: front-end
