apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: LoadBalancer # Only works on cloud providers
  ports:
    - port: 80 # Only port field is mandatory (service)
      targetPort: 80 # Default value is same as port (backend)
  selector:
    app: myapp
    type: back-end
