apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80 # Only port field is mandatory
      targetPort: 80 # Default value is same as port
      nodePort: 30008 # Default value is random
  selector:
    app: myapp
    type: front-end
